baseURL = "cdecker.io"
defaultContentLanguage = "en"
languageCode = "en"
title = "cdeckerio"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  #  LoveIt theme version
  version = "0.2.X"
  defaultTheme = "dark"
  keywords = ["hugo", "consulting", "backend"]
  gitRepo = "https://github.com/redspart"
  fingerprint = "sha512"
  dateFormat = "2020-01-02"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Christian Decker"
      typeit = false

  [params.footer]
    enabled = false
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2019
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  [params.social]
    Github = "redspart"
    Linkedin = "christian-decker-01a25280"
    Email = "christian@cdecker.io"
    RSS = false

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpeg"
      title = "Sr. Infrastructure Engineer"
      subtitle = "This is My New Hugo Site"
      typeit = false 
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    fontawesome = true
    ruby = true
    python = true
    linkToMarkdown = true
    [params.page.toc]
      enable = true
      keepStatic = true
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 10
    [params.page.share]
      enable = true
      Twitter = true
      Linkedin = true
      HackerNews = true
      Reddit = true
    [params.page.comment]
      enable = false 


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false